// State de firebase
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_USUARIO_FIRESTORE = 'OBTENER_USUARIO_FIRESTORE';
export const OBTENER_RESTAURANTES = 'OBTENER_RESTAURANTES';
export const OBTENER_PRODUCTOS_RESTAURANTE = 'OBTENER_PRODUCTOS_RESTAURANTE';
export const OBTENER_CLIENTE_ORDEN = 'OBTENER_CLIENTE_ORDEN';
export const OBTENER_RESTAURANTE_ORDEN = 'OBTENER_RESTAURANTE_ORDEN';
export const OBTENER_RESTAURANTE_BY_ID = 'OBTENER_RESTAURANTE_BY_ID';
export const OBTENER_CONFIGS = 'OBTENER_CONFIGS';

// State de pedido
export const LISTAR_PRODUCTOS = 'LISTAR_PRODUCTOS';
export const LISTAR_PRODUCTOS_CATEGORIA = 'LISTAR_PRODUCTOS_CATEGORIA';
export const LISTAR_PRODUCTOS_BUSQUEDA = 'LISTAR_PRODUCTOS_BUSQUEDA';
export const LIMPIAR_LISTA_PRODUCTOS = 'LIMPIAR_LISTA_PRODUCTOS';
export const LIMPIAR_LISTA_PRODUCTOS_CATEGORIA = 'LIMPIAR_LISTA_PRODUCTOS_CATEGORIA';
export const LIMPIAR_LISTA_PRODUCTOS_BUSQUEDA = 'LIMPIAR_LISTA_PRODUCTOS_BUSQUEDA';
export const SELECCIONAR_NEGOCIO = 'SELECCIONAR_NEGOCIO';
export const SELECCIONAR_CATEGORIA = 'SELECCIONAR_CATEGORIA';
export const SELECCIONAR_RESTAURANTE = 'SELECCIONAR_RESTAURANTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const AGREGAR_PRODUCTO_FAVORITO = 'AGREGAR_PRODUCTO_FAVORITO';
export const ELIMINAR_PRODUCTO_FAVORITO = 'ELIMINAR_PRODUCTO_FAVORITO';
export const AGREGAR_PRODUCTO_CARRITO = 'AGREGAR_PRODUCTO_CARRITO';
export const ELIMINAR_PRODUCTO_CARRITO = 'ELIMINAR_PRODUCTO_CARRITO';
export const PAGO_TOTAL = 'PAGO_TOTAL';
export const CANTIDAD_TOTAL = 'CANTIDAD_TOTAL';
export const TIEMPO_ENTREGA = 'TIEMPO_ENTREGA';
export const DIRECCION_ORIGEN = 'DIRECCION_ORIGEN';
export const DIRECCION_DESTINO = 'DIRECCION_DESTINO';
export const PEDIDO_REALIZADO = 'PEDIDO_REALIZADO';
export const GUARDAR_PEDIDO = 'GUARDAR_PEDIDO';
